// Mnemonic System (Spanish Major System)
// R = 0; S, Z = 5;
// L = 1; G = 6;
// D = 2; T = 7;
// M = 3; B, V = 8;
// C, Q, K = 4; N, Ñ = 9;
// COMODINES (wildcards): A, E, I, O, U, X, Y, H, F, J, P, W

const CODE_MAP = {
    'r': '0',
    'l': '1',
    'd': '2',
    'm': '3',
    'c': '4', 'q': '4', 'k': '4',
    's': '5', 'z': '5',
    'g': '6',
    't': '7',
    'b': '8', 'v': '8',
    'n': '9', 'ñ': '9'
};

// Convert word to number code
function wordToCode(word) {
    let code = "";
    const normalized = word.toLowerCase().normalize("NFD").replace(/[\u0301]/g, "");
    for (const char of normalized) {
        if (CODE_MAP[char] !== undefined) {
            code += CODE_MAP[char];
        }
    }
    return code;
}

// Base words for 0-9 and 00-99 (your original curated list)
const BASE_WORDS = [
    // 0-9
    "ORO", "HIELO", "JUDIO", "MAIA", "COPA", "SEXO", "AGUA", "TIO", "UBA", "PEON",
    // 00-99
    "PERRO", "RELOJ", "RUEDA", "ARMA", "ROCO", "ROSA", "ORGIA", "RATA", "RUBIA", "RANA",
    "PILAR", "LILA", "HELADO", "PLUMA", "POLICIA", "ALAS", "LAGO", "LATA", "LOBO", "ALAN",
    "PIEDRA", "DOLO", "DADO", "DAMA", "DUKI", "DIOS", "DIEGO", "DT", "DIBUJO", "DANI",
    "FUMAR", "MILI", "MOJADO", "MAMA", "MOCO", "MESA", "MAGO", "MATE", "PUMBA", "MONO",
    "CARO", "CULO", "PICADA", "CAMA", "COCA", "CASA", "CAGA", "PACTO", "CUBA", "CHINO",
    "SURF", "SOL", "ASADO", "ESPUMA", "SACO", "OSOS", "SOGA", "ZAPATO", "SUBE", "SONIA",
    "JUGAR", "GOL", "GUIDO", "GOMA", "AGACHA", "GUISO", "GAGO", "GATO", "GUIABA", "GENIO",
    "TORO", "TELA", "ATAUD", "TIEMPO", "TACHO", "FOTOS", "FATIGA", "TUTE", "TUBO", "ATUN",
    "BRUJA", "PABLO", "ABADE", "BOHEMIO", "VACA", "HUEVOS", "VAGA", "BATA", "BOBE", "JABON"
];

// Extended words (your additions + new memorable nouns)
const EXTENDED_WORDS = [
    // Your original additions
    "MARADONA", "PARLANTE", "TENEDOR", "TOALLA", "CUADRO", "BOLSA", "BARBIE", "TRUCO",
    "ROLLO", "CABLE", "COMPUTADORA", "PATOVICA", "PARAGUAS", "BALDE", "CANILLA", "ESCUDO",
    "DIENTES", "CANILLERA", "ABOGADO", "SORDA", "TABLA", "RIVER", "ATLANTA", "RACING",
    "AMBULANCIA", "ANGEL", "ANILLO", "ANTARTIDA", "ANTORCHA", "ARGENTINA", "ARTICULO",
    "ATLANTIDA", "AZTECA", "BALLENA", "BANCO", "BANDA", "BARCO", "BATERIA", "BOMBA",
    "BOSQUE", "BOTELLA", "BOTON", "BRAZO", "CABALLERO", "CABEZA", "CACTUS", "CADENA",
    "CAMARA", "CAMBIO", "CAMPANA", "CARRERA", "CARRO", "CARTA", "CASCO", "CASINO",
    "CEMENTERIO", "CENTAURO", "CHOCOLATE", "CIENTIFICO", "CINTA", "CINTURON", "CIRCULO",
    "COCINERO", "CODIGO", "CANGURO", "CONCIERTO", "CORREDOR", "CRESTA", "CRUZ", "CUCHILLO",
    "CUELLO", "CUERNO", "DIAMANTE", "DIENTE", "DINOSAURIO", "DISCO", "DRAGON", "DUENDE",
    "EMBAJADA", "EMPERADOR", "ENFERMERA", "ESCORPION", "ESTADIO", "ESTRELLA", "ETIQUETA",
    "FRENTE", "GANCHO", "GIGANTE", "GRANADA", "GRANO", "GRIEGO", "HELICOPTERO", "INGLATERRA",
    "LASER", "LATIGO", "LENGUA", "LIMUSINA", "LISTA", "LLAVE", "LONDRES", "MANCHA",
    "MASCARA", "SUBTE", "MICROSCOPIO", "COLUMNA", "MISIL", "MORTERO", "MOTOR", "CORAZON",
    "PANTALLA", "PARACAIDAS", "MODELO", "DOCTOR", "MAESTRO", "MILLONARIO", "SOLDADO",
    "BANANA", "MANZANA", "FRUTILLA", "MORRON", "ZANAHORIA", "TOMATE", "MANGO", "AMARILLO",
    "NARANJA", "VERDE", "VIOLETA", "BLANCO", "NEGRO", "VESTIDO", "BERMUDAS", "JOGGING",
    "ZAPATILLA", "MEDIAS", "CALZON", "TANGA", "PANTUFLAS", "CAMISA", "GORRA", "REMERA",
    "SWEATER", "GUANTES", "ORNITORRINCO", "CABALLO", "GUSANO", "GOLONDRINA", "PINGUINO",
    "LLAMA", "UNICORNIO", "SERPIENTE", "SIRENA", "PRINCESA", "SUPERMAN", "LADRON",
    "VAMPIRO", "BATMAN", "LINTERNA", "SPIDERMAN", "CAPITAN", "AMERICA", "EXTRATERRESTRE",
    "FANTASMA", "BRITNEY", "BEATLES", "MARILYN", "CHANDLER", "RACHEL", "ROSS",

    // Animals
    "ABEJA", "AGUILA", "ALACRAN", "ARAÑA", "ARDILLA", "ARMADILLO", "BUHO", "BURRO",
    "CABRA", "CAMALEON", "CAMELLO", "CANGREJO", "CEBRA", "CERDO", "CIGUEÑA", "CISNE",
    "COCODRILO", "COLIBRI", "CONEJO", "CUERVO", "DELFIN", "ELEFANTE", "ERIZO", "ESCORPION",
    "FLAMINGO", "FOCA", "GALLINA", "GANSO", "GALLO", "GORILA", "GRILLO", "HALCON",
    "HAMSTER", "HIPOPOTAMO", "HORMIGA", "IGUANA", "JAGUAR", "JIRAFA", "KOALA", "LAGARTO",
    "LANGOSTA", "LECHUZA", "LEON", "LEOPARDO", "LIEBRE", "LORITO", "LORO", "MARIPOSA",
    "MEDUSA", "MONO", "MORSA", "MOSCA", "MOSQUITO", "MURCIELAGO", "NUTRIA", "OSO",
    "OVEJA", "PANDA", "PANTERA", "PATO", "PAVO", "PELICANO", "PERRO", "PULPO",
    "PUMA", "RATON", "RINOCERONTE", "SALMON", "SAPO", "SARDINA", "SERPIENTE", "TIGRE",
    "TIBURON", "TORTUGA", "TRUCHA", "VACA", "ZORRO",

    // Food & Drinks
    "ACEITE", "ACEITUNA", "AGUACATE", "AJO", "ALBONDIGA", "ALMENDRA", "ANCHOA", "ARROZ",
    "ATUN", "AVENA", "AZUCAR", "BACON", "BATIDO", "BERRO", "BROCOLI", "CAFE", "CALABAZA",
    "CALAMARES", "CALDO", "CANELA", "CARAMELO", "CARNE", "CEBOLLA", "CEREZA", "CERVEZA",
    "CHAMPAN", "CHICLE", "CHORIZO", "CHURRO", "CIRUELA", "COCO", "COLIFLOR", "CREMA",
    "CROISSANT", "DONUT", "DURAZNO", "EMPANADA", "ENSALADA", "ESPAGUETI", "ESPINACA",
    "FIDEO", "FLAN", "FRAMBUESA", "FRESA", "GALLETA", "GARBANZO", "GINEBRA", "GUISANTE",
    "HAMBURGUESA", "HELADO", "HIGO", "HUEVO", "JAMON", "JUGO", "KETCHUP", 
    "LASAÑA", "LECHE", "LECHUGA", "LENTEJA", "LIMON", "LONGANIZA", "MACARRONES",
    "MAYONESA", "MELON", "MENTA", "MERLUZA", "MERMELADA", "MIEL", "MOSTAZA", "NARANJA",
    "NATA", "NUEZ", "PAELLA", "PAN", "PANCHO", "PAPAYA", "PASTEL", "PEPINO", "PERA",
    "PESCADO", "PIMIENTA", "PIÑA", "PIZZA", "PLATANO", "POLLO", "POMELO", "PRETZEL",
    "QUESO", "RABANO", "RAVIOLI", "REPOLLO", "RISOTTO", "RON", "SAL", "SALCHICHA",
    "SALMON", "SANDIA", "SARDINA", "SOPA", "SUSHI", "TACO", "TE", "TERNERA", "TOCINO",
    "TOFU", "TOSTADA", "UVA", "VAINILLA", "VINAGRE", "VINO", "VODKA", "YOGUR",
    "ZANAHORIA",

    // Objects & Tools
    "ALFOMBRA", "ALMOHADA", "ANCLA", "ANTENA", "ANUNCIO", "ARMARIO", "ASPIRADORA",
    "BALCON", "BALON", "BANDERA", "BAÑERA", "BASURA", "BILLETERA", "BINOCULARES",
    "BRUJULA", "CAFETERA", "CAJA", "CAJON", "CALCULADORA", "CALENDARIO", "CAMA",
    "CANDADO", "CAÑON", "CARTEL", "CARTERA", "CEPILLO", "CERRADURA", "CHALECO",
    "CHIMENEA", "CLAVIJA", "CLIP", "COLCHON", "COLGADOR", "COLLAR", "CORTINA",
    "CUADERNO", "CUCHARA", "DESTORNILLADOR", "ENCHUFE", "ESCALERA", "ESCOBA",
    "ESCRITORIO", "ESPADA", "ESPEJO", "ESPONJA", "ESTANTE", "ESTUFA", "EXTINTOR",
    "FLORERO", "FOCO", "FOGATA", "FORRO", "FUENTE", "GANCHO", "GRIFO", "GRUA",
    "HACHA", "HORNO", "IMANES", "IMPRESORA", "INTERRUPTOR", "JAULA", "JARRA",
    "JARRON", "JERSEYS", "JOYSTICK", "LAMPARA", "LAPIZ", "LAVADORA", "LAVAPLATOS",
    "LIBRETA", "LIBRO", "LICUADORA", "LUPA", "MALETIN", "MANGUERA", "MANTA",
    "MARTILLO", "MECHERO", "MICROONDAS", "MONITOR", "MOCHILA", "MOLINO", "MONEDA",
    "NAVAJA", "NEVERA", "OLLA", "ORDENADOR", "PALA", "PALANCA", "PANTALLA",
    "PAPEL", "PARAGUAS", "PEINE", "PERCHA", "PICAPORTE", "PILA", "PINCEL",
    "PINTURA", "PINZA", "PISCINA", "PISTOLA", "PIZARRA", "PLANCHA", "PLANTA",
    "PLATO", "PLUMA", "PUERTA", "RADIO", "REGADERA", "REGLA", "RELOJ", "REVISTA",
    "RIFLE", "RUEDA", "SABANA", "SACAPUNTAS", "SARTEN", "SECADOR", "SEMAFORO",
    "SERVILLETA", "SIERRA", "SILBATO", "SILLA", "SOFA", "TABURETE", "TALADRO",
    "TAMBOR", "TARJETA", "TAZA", "TECLADO", "TELEFONO", "TELESCOPIO", "TELEVISION",
    "TENEDOR", "TERMO", "TERMOMETRO", "TIJERAS", "TIMBRE", "TIMON", "TINTERO",
    "TOALLA", "TORNILLO", "TRAPEADOR", "TROMPETA", "TUBO", "TUERCA", "VASO",
    "VELA", "VENTANA", "VENTILADOR", "VOLANTE",

    // Body Parts
    "BARBA", "BARBILLA", "BIGOTE", "BOCA", "BRAZO", "CADERA", "CARA", "CEJA",
    "CEREBRO", "CINTURA", "CODO", "CORAZON", "COSTILLA", "CRANEO", "CUELLO",
    "DEDO", "ESPALDA", "ESTOMAGO", "FRENTE", "GARGANTA", "HIGADO", "HOMBRO",
    "HUESO", "INTESTINO", "LABIO", "LENGUA", "MANO", "MEJILLA", "MENTON",
    "MUÑECA", "MUSCULO", "MUSLO", "NARIZ", "NUCA", "OJO", "OMBLIGO", "OREJA",
    "PANTORRILLA", "PESTAÑA",
    "PIERNA", "PULGAR", "PULMON", "RINON", "RODILLA", "SANGRE", "TALON",
    "TOBILLO", "TORSO", "UÑA",

    // Professions & People
    "ABOGADO", "ACTOR", "ACTRIZ", "ALBAÑIL", "ALCALDE", "ARBITRO", "ARQUITECTO",
    "ARTISTA", "ASTRONAUTA", "ATLETA", "BARBERO", "BOMBERO", "BOXEADOR", "BRUJO",
    "CANTANTE", "CAPITAN", "CARNICERO", "CARPINTERO", "CARTERO", "CHEF", "CHOFER",
    "CIRUJANO", "COMEDIANTE", "CONDUCTOR", "COCINERO", "DENTISTA", "DETECTIVE",
    "DICTADOR", "DIRECTOR", "DOCTOR", "ELECTRICISTA", "EMPERADOR", "ENFERMERO",
    "ESCRITOR", "ESPIA", "ESTUDIANTE", "FARMACEUTICO", "FILOSOFO", "FISCAL",
    "FOTOGRAFO", "FUTBOLISTA", "GERENTE", "GLADIADOR", "GOBERNADOR", "GUARDIA",
    "GUITARRISTA", "HEROE", "HISTORIADOR", "INGENIERO", "INSTRUCTOR", "JARDINERO",
    "JINETE", "JUEZ", "JUGADOR", "KARATECA", "MAGO", "MARINERO", "MECANICO",
    "MEDICO", "MESERO", "MILITAR", "MINERO", "MONJA", "MONJE", "MUSICO",
    "NADADOR", "NINJA", "PAYASO", "PERIODISTA", "PILOTO", "PINTOR", "PIRATA",
    "PLOMERO", "POETA", "POLICIA", "POLITICO", "PRESIDENTE", "PRINCIPE",
    "PRINCESA", "PROFESOR", "PROGRAMADOR", "PSICOLOGO", "RAPERO", "REY",
    "REINA", "REPORTERO", "ROBOT", "SACERDOTE", "SAMURAI", "SASTRE", "SENADOR",
    "SERVIDOR", "SHERIFF", "SOLDADO", "SURFISTA", "TAXISTA", "TENISTA",
    "TERRORISTA", "TORERO", "TRABAJADOR", "VAMPIRO", "VENDEDOR", "VETERINARIO",
    "VIKINGO", "VOCALISTA", "ZAPATERO", "ZOMBI",

    // Places & Buildings
    "AEROPUERTO", "ALMACEN", "ALTAR", "APARTAMENTO", "ARENA", "AUTOPISTA",
    "BALNEARIO", "BAR", "BIBLIOTECA", "BODEGA", "BOLICHE", "BUNKER", "CABINA",
    "CALABOZO", "CALLEJON", "CANCHA", "CAPILLA", "CARCEL", "CARNICERIA",
    "CASCADA", "CASTILLO", "CATEDRAL", "CEMENTERIO", "CENTRO", "CHOZA",
    "CINE", "CIRCO", "CLUB", "COCINA", "COLISEO", "COMEDOR", "COMISARIA",
    "CONVENTO", "CUARTEL", "CUEVA", "DEPOSITO", "DESIERTO", "DISCOTECA",
    "EDIFICIO", "EMBAJADA", "ESCUELA", "ESTABLO", "ESTACION", "ESTADIO",
    "FABRICA", "FARMACIA", "FARO", "FORTALEZA", "FRONTERA", "FUENTE",
    "GASOLINERA", "GIMNASIO", "GRANJA", "GUARIDA", "HABITACION", "HANGAR",
    "HIPERMERCADO", "HOSPITAL", "HOSTAL", "HOTEL", "IGLESIA", "INVERNADERO",
    "ISLA", "JARDIN", "JUNGLA", "KIOSCO", "LABORATORIO", "LABERINTO",
    "LAGUNA", "LAVADERO", "LIBRERIA", "MANSION", "MAUSOLEO", "MERCADO",
    "MEZQUITA", "MINA", "MIRADOR", "MOLINO", "MONASTERIO", "MONTAÑA",
    "MONUMENTO", "MORGUE", "MUELLE", "MUNICIPIO", "MUSEO", "OASIS",
    "OBSERVATORIO", "OCEANO", "OFICINA", "PALACIO", "PANTANO", "PARQUE",
    "PASILLO", "PELUQUERIA", "PENITENCIARIA", "PIRAMIDE", "PISCINA",
    "PLATAFORMA", "PLAYA", "PLAZA", "PORTAL", "PRISION", "PROSTIBULO",
    "PUENTE", "PUERTO", "QUINTA", "RANCHO", "REFUGIO", "RESTAURANTE",
    "RIO", "RINCON", "SALON", "SANTUARIO", "SELVA", "SENDERO", "SINAGOGA",
    "SOTANO", "SUPERMERCADO", "TALLER", "TEATRO", "TEMPLO", "TERRAZA",
    "TIENDA", "TORRE", "TUNEL", "UNIVERSIDAD", "VALLE", "VECINDARIO",
    "VOLCÁN", "ZOOLOGICO",

    // Vehicles & Transportation
    "AMBULANCIA", "AUTOBUS", "AVION", "BARCO", "BICICLETA", "BOTE", "CAMION",
    "CANOA", "CARRETA", "CARRO", "COHETE", "COLECTIVO", "FURGONETA", "GLOBO",
    "HELICOPTERO", "JEEP", "JET", "KAYAK", "LANCHA", "LIMUSINA", "LOCOMOTORA",
    "METRO", "MOTO", "NAVE", "OMNIBUS", "OVNI", "PARACAIDAS", "PATINETA",
    "SCOOTER", "SUBMARINO", "TANQUE", "TAXI", "TELEFÉRICO", "TRACTOR", "TRANVIA",
    "TREN", "TRICICLO", "TRINEO", "VELERO", "YATE", "ZEPPELIN",

    // Sports & Games
    "ARQUERO", "ARCO", "ARBITRO", "BALON", "BASQUET", "BILLAR", "BOXEO",
    "CANCHA", "CARRERA", "DADO", "DARDO", "DOMINO", "ESCALADA", "ESGRIMA",
    "ESQUI", "FUTBOL", "GOLF", "HOCKEY", "JUDO", "KARATE", "LUCHA", "MARATON",
    "NATACION", "OLIMPIADA", "PADDLE", "PELOTA", "PING", "PONG", "POKER",
    "POLO", "PORTERO", "RAQUETA", "RED", "RUGBY", "SALTO", "TENIS", "TORNEO",
    "VOLEY", "YOGA",

    // Music & Entertainment
    "ACORDEON", "ALBUM", "ARPA", "BAJO", "BANJO", "BATERIA", "CAMPANA",
    "CANCION", "CELLO", "CLARINETE", "CONCIERTO", "CONTRABAJO", "CORO",
    "DISCO", "ESCENARIO", "FLAUTA", "GUITARRA", "MARACAS", "MELODIA",
    "MICROFONO", "ORQUESTA", "PANDERO", "PIANO", "SAXOFON", "TAMBOR",
    "TRIANGULO", "TROMPETA", "VIOLIN", "XILOFONO",

    // Nature & Weather
    "ARBOL", "ARBUSTO", "ARENA", "ARROYO", "AURORA", "AVALANCHA", "BOSQUE",
    "BRISA", "CASCADA", "CIELO", "COLINA", "COMETA", "CORAL", "CUMBRE",
    "DUNA", "ECLIPSE", "ESTRELLA", "FLOR", "GLACIAR", "GRANIZO", "HIERBA",
    "HOJA", "HURACAN", "ICEBERG", "LAGO", "LAVA", "LLUVIA", "LUNA", "MAR",
    "MAREMOTO", "NIEBLA", "NIEVE", "NUBE", "OCEANO", "OLA", "PANTANO",
    "PLANTA", "PRADERA", "RAYO", "ROCA", "ROSA", "SELVA", "SOL", "SOMBRA",
    "TERREMOTO", "TIERRA", "TORNADO", "TORMENTA", "TRUENO", "TSUNAMI",
    "VIENTO", "VOLCAN",

    // Technology & Science
    "ANTENA", "ATOMO", "BATERIA", "CALCULADORA", "CAMARA", "CELULAR",
    "CHIP", "CIRCUITO", "COMPUTADORA", "CONSOLA", "DRON", "ELECTRODO",
    "ENERGIA", "GALAXIA", "GPS", "GRAVEDAD", "IMPRESORA", "INTERNET",
    "LASER", "LENTE", "MONITOR", "MOUSE", "NAVE", "NEURONA", "ORBITA",
    "PANTALLA", "PLANETA", "PLASMA", "PROCESADOR", "RADAR", "RADIO",
    "REACTOR", "ROBOT", "SATELITE", "SENSOR", "SERVIDOR", "SISTEMA", "TABLETA", "TECLADO", "TELESCOPIO", "USB", "VACUNA",
    "VIRUS", "WIFI",

    // Fantasy & Mythology
    "ANGEL", "CENTAURO", "CICLOPE", "DEMONIO", "DRAGON", "DUENDE", "ELFO",
    "FANTASMA", "FENIX", "GIGANTE", "GNOMO", "GOBLIN", "GRIFO", "HADA",
    "HIDRA", "KRAKEN", "MEDUSA", "MINOTAURO", "MOMIA", "MONSTRUO", "OGRO",
    "PEGASO", "SIRENA", "TROLL", "UNICORNIO", "VAMPIRO", "YETI", "ZOMBIE",

    // Clothing & Accessories
    "ANILLO", "ANTEOJOS", "BILLETERA", "BLUSA", "BOLSO", "BOTAS", "BUFANDA",
    "CADENA", "CALCETIN", "CAMPERA", "CAPA", "CARTERA", "CHALECO", "CHAQUETA",
    "CINTURON", "COLLAR", "CORBATA", "CORONA", "DELANTAL", "DIADEMA", "FALDA",
    "GAFAS", "GORRA", "GUANTE", "JEAN", "JOYA", "LENTES", "MANGA", "MASCARA",
    "MOCHILA", "OJOTAS", "PANTALON", "PAÑUELO", "PIJAMA", "POLLERA", "PULCERA",
    "RELOJ", "REMERA", "ROPA", "SANDALIAS", "SOMBRERO", "SUETER", "TRAJE",
    "VESTIDO", "ZAPATO", "ZAPATILLAS",

    // Emotions & Abstract
    "ALEGRIA", "ALMA", "AMOR", "ANGUSTIA", "ANSIEDAD", "CAOS", "CARIÑO",
    "CERTEZA", "CORAJE", "DESTINO", "DOLOR", "DUDA", "ESPERANZA", "EXITO",
    "FE", "FELICIDAD", "FUERZA", "FURIA", "GLORIA", "IDEA", "KARMA",
    "LOCURA", "LUZ", "MAGIA", "MEMORIA", "MENTE", "MIEDO", "MUERTE",
    "NOSTALGIA", "ODIO", "ORGULLO", "PASION", "PAZ", "PENA", "PLACER",
    "PODER", "RABIA", "RECUERDO", "SABIDURIA", "SILENCIO", "SUEÑO",
    "SUERTE", "TEMOR", "TIEMPO", "VERDAD", "VICTORIA", "VIDA",

    // Colors & Materials
    "ACERO", "ALUMINIO", "ARCILLA", "ARENA", "BRONCE", "CARBON", "CEMENTO",
    "CERAMICA", "COBRE", "CRISTAL", "CUERO", "DIAMANTE", "ESMERALDA", "GOMA",
    "HIERRO", "LANA", "LADRILLO", "MADERA", "MARMOL", "METAL", "ORO",
    "PAPEL", "PIEDRA", "PLATA", "PLASTICO", "PORCELANA", "RUBI", "SEDA",
    "TELA", "TERCIOPELO", "TITANIO", "VIDRIO", "ZAFIRO",

    // Actions as nouns (memorable images)
    "ABRAZO", "APLAUSO", "BESO", "CAIDA", "CARICIA", "CHOQUE", "DANZA",
    "DISPARO", "EXPLOSION", "GRITO", "MORDIDA", "PATADA", "PELEA",
    "PIRUETA", "PUÑETAZO", "SALTO", "VUELO",

    // Famous characters & brands (memorable)
    "HULK", "IRONMAN", "THOR", "JOKER", "SHREK", "PIKACHU", "GOKU",
    "NARUTO", "MESSI", "RONALDO", "PELE", "JORDAN", "TYSON", "ALI",
    "ELVIS", "MADONNA", "SHAKIRA", "BEYONCE", "DRAKE", "EMINEM",
    "EINSTEIN", "NEWTON", "DARWIN", "FREUD", "PICASSO", "DALI",
    "BEETHOVEN", "MOZART", "DISNEY", "MICKEY", "DONALD", "PLUTO",
    "SIMPSONS", "HOMER", "BART", "LISA", "MARGE", "VADER", "YODA",
    "CHEWBACCA", "GANDALF", "FRODO", "GOLLUM", "HAGRID", "DUMBLEDORE",
    "VOLDEMORT", "HARRY", "HERMIONE", "TARZAN", "PINOCHO", "CENICIENTA",
    "BLANCANIEVES", "RAPUNZEL", "ELSA", "MOANA", "NEMO", "DORY",
    "WOODY", "BUZZ", "SHREK", "FIONA", "BURRO",

    // ============ FAMOUS PEOPLE - EXPANDED ============

    // Football/Soccer Players
    "NEYMAR", "HAALAND", "BENZEMA", "MODRIC", "KROOS",
    "ZIDANE", "RONALDINHO", "KAKA", "BECKHAM", "ROONEY", "GERRARD",
    "LAMPARD", "TERRY", "HENRY", "BERGKAMP", "PIRLO", "TOTTI",
    "BUFFON", "CASILLAS", "NEUER", "OBLAK", "COURTOIS", "ALISSON",
    "SALAH", "MANE", "FIRMINO", "SUAREZ", "CAVANI", "GRIEZMANN",
    "POGBA", "KANTE", "HAZARD", "LUKAKU", "LEWANDOWSKI", "MULLER",
    "RAMOS", "PIQUE", "PUYOL", "XAVI", "INIESTA", "BUSQUETS",
     "VINICIUS", "RODRIGO", "FODEN",
    "MOUNT", "PALMER",
    "BATISTUTA", "CRESPO", "VERON", "ZANETTI", "SAMUEL", "CAMBIASSO",
    "RIQUELME", "SAVIOLA", "TEVEZ",
    "DIMARIA", "DYBALA", "LAUTARO", "ALVAREZ", "GARNACHO", "ENZO",
    "KEMPES", "PASSARELLA", "FILLOL", "VALDANO",
    "CANIGGIA", "REDONDO", "SIMEONE", "ORTEGA", "GALLARDO", "PALERMO",

    // Basketball Players
    "LEBRON", "KOBE", "SHAQ", "DUNCAN", 
    "WADE", "BOSH", "PAUL", "WESTBROOK", "DURANT", "CURRY",
    "THOMPSON", "GREEN", "IRVING", "LOVE", "HARDEN", "KAWHI",
    "LEONARD", "GEORGE", "BUTLER", "BEAL", "BOOKER", "TATUM",
    "BROWN", "SMART", "JOKIC", "EMBIID", "GIANNIS", "LILLARD",
    "DONCIC", "MORANT", "EDWARDS", "WEMBANYAMA", "GINOBILI", "SCOLA",
    "NOCIONI", "DELFINO", "PRIGIONI", "CAMPAZZO", "DECK", "LAPROVITTOLA",

    // Tennis Players
    "FEDERER", "NADAL", "DJOKOVIC", "MURRAY", "WAWRINKA", "THIEM",
    "ZVEREV", "TSITSIPAS", "MEDVEDEV", "RUBLEV", "SINNER", "ALCARAZ",
    "RUUD", "NORRIE", "TIAFOE", "FRITZ", "DELPO", "NALBANDIAN",
    "GAUDIO", "CORIA", "VILAS", "CLERC", "SABATINI", "SERENA",
    "VENUS", "SHARAPOVA", "OSAKA", "SWIATEK", "SABALENKA", "GAUFF",


    "SODA", "STEREO", "CERATI", "CHARLY", "GARCIA", "SPINETTA",
    "FITO", "PAEZ", "CALAMARO",
    "MERCEDES", "GARDEL",


    // ============ CHILDREN'S VOCABULARY ============

    // Toys & Play
    "MUÑECA", "PELUCHE", "OSITO", "COCHECITO", "CARRITO", "TRENECITO",
    "AVIONCITO", "BARQUITO", "PELOTITA", "GLOBITO", "POMPAS", "BURBUJAS",
    "ROMPECABEZAS", "PUZZLE", "LEGO", "BLOQUES", "CUBOS", "FICHAS",
    "CANICAS", "BOLITAS", "YOYO", "TROMPO", "COMETA", "PAPALOTE",
    "SUBE", "BAJA", "COLUMPIO", "TOBOGAN", "RESBALIN", "HAMACA",
    "CALESITA", "CARRUSEL", "NORIA", "SALTARIN", "CAMA", "ELASTICA",
    "TRAMPOLIN", "PATIN", "PATINES", "PATINETA", "MONOPATÍN", "SCOOTER",
    "BICICLETA", "TRICICLO", "CUATRICICLO", "CABALLITO", "MECEDORA",
    "SONAJERO", "CHUPETE", "MAMADERA", "BIBERON", "BABERO", "PAÑAL",

    // School Supplies
    "LAPIZ", "LAPICERA", "BIROME", "MARCADOR", "FIBRA", "FIBRÓN",
    "CRAYÓN", "CRAYOLA", "TEMPERA", "ACUARELA", "PINCEL", "PALETA",
    "TIJERA", "TIJERITAS", "PLASTICOLA", "PEGAMENTO", "CINTA", "SCOTCH",
    "GOMA", "BORRADOR", "SACAPUNTAS", "REGLA", "ESCUADRA", "COMPAS",
    "CARTUCHERA", "MOCHILA", "CARPETA", "CUADERNO", "LIBRETA", "BLOCK",
    "HOJA", "PAPEL", "CARTULINA", "CARTÓN", "PIZARRÓN", "TIZA",
    "BORRADOR", "FIAMBRERAS", "LONCHERA", "TERMO", "BOTELLA",

    // Simple Animals (child-friendly)
    "PERRITO", "GATITO", "PAJARITO", "POLLITO", "PATITO", "CONEJITO",
    "RATONCITO", "OSITO", "CERDITO", "VAQUITA", "OVEJITA", "CABALLITO",
    "BURRITO", "PONNY", "MONITO", "ELEFANTITO", "JIRAFITA", "LEONCITO",
    "TIGRECITO", "ZEBRA", "HIPOPOTAMO", "RINOCERONTE", "COCODRILO",
    "CAIMÁN", "LAGARTIJA", "IGUANA", "TORTUGA", "CARACOL", "BABOSA",
    "ORUGA", "MARIPOSA", "ABEJA", "AVISPA", "MOSCA", "MOSQUITO",
    "HORMIGA", "ARAÑA", "CUCARACHA", "GRILLO", "SALTAMONTES", "LIBÉLULA",
    "MARIQUITA", "ESCARABAJO", "LUCIÉRNAGA", "CIEMPIÉS", "GUSANO",
    "LOMBRIZ", "RENACUAJO", "RANA", "SAPO", "PECECITO", "PECERA",
    "TORTUGA", "HAMSTER", "COBAYO", "CONEJO", "LORO", "CANARIO",

    // Food Kids Love
    "CARAMELO", "CHUPETÍN", "PALETA", "PIRULETA", "CHICLE", "GOMITA",
    "OSITOS", "CHOCOLATÍN", "GALLETITA", "ALFAJOR", "BIZCOCHO",
    "TORTA", "PASTEL", "MAGDALENA", "MUFFIN", "CUPCAKE", "DONUT",
    "PANQUEQUE", "WAFFLE", "CREPE", "TOSTADA", "MERMELADA", "DULCE",
    "NUTELLA", "MANTECA", "QUESO", "JAMON", "FIAMBRE", "SALCHICHA",
    "HAMBURGUESA", "PANCHOS", "PATITAS", "NUGGETS", "PAPAS", "FRITAS",
    "PIZZA", "FIDEOS", "ARROZ", "PURE", "MILANESA", "EMPANADA",
    "TARTA", "JUGO", "JUGUITO", "CHOCOLATADA", "LECHE", "YOGUR",
    "FRUTILLA", "BANANA", "MANZANA", "NARANJA", "MANDARINA", "UVA",
    "SANDIA", "MELON", "DURAZNO", "PERA", "KIWI", "CEREZA",

    // Home Objects
    "CASA", "CASITA", "CUARTO", "PIEZA", "COCINA", "BAÑO",
    "LIVING", "COMEDOR", "DORMITORIO", "BALCON", "JARDIN", "PATIO",
    "PUERTA", "VENTANA", "TECHO", "PISO", "PARED", "ESCALERA",
    "ASCENSOR", "TIMBRE", "LLAVE", "CERRADURA", "PICAPORTE",
    "MESA", "SILLA", "SILLON", "SOFA", "CAMA", "CUNA",
    "ALMOHADA", "SABANA", "FRAZADA", "COLCHA", "ACOLCHADO",
    "LAMPARA", "LUZ", "FOCO", "VELADOR", "ARAÑA", "VENTILADOR",
    "AIRE", "CALEFACTOR", "ESTUFA", "RADIADOR", "TELEVISOR", "TELE",
    "CONTROL", "REMOTO", "COMPUTADORA", "COMPU", "TABLET", "CELULAR",
    "TELEFONO", "RADIO", "PARLANTE", "AURICULAR", "ENCHUFE",
    "HELADERA", "FREEZER", "MICROONDAS", "HORNO", "COCINA",
    "TOSTADORA", "LICUADORA", "BATIDORA", "CAFETERA", "PAVA",
    "OLLA", "SARTEN", "CACEROLA", "FUENTE", "PLATO", "TAZA",
    "VASO", "COPA", "JARRA", "BOTELLA", "CUCHARA", "TENEDOR",
    "CUCHILLO", "SERVILLETA", "MANTEL", "REPASADOR", "TRAPO",

    // Body Parts (child-friendly)
    "CABEZA", "PELO", "CABELLO", "CARA", "FRENTE", "CEJA",
    "OJO", "OJITO", "OREJA", "NARIZ", "NARICITA", "BOCA",
    "LABIO", "DIENTE", "DIENTITO", "LENGUA", "MENTON", "CACHETE",
    "CUELLO", "HOMBRO", "BRAZO", "CODO", "MUÑECA", "MANO",
    "DEDO", "DEDITO", "UÑA", "PANZA", "OMBLIGO", "ESPALDA",
    "COLA", "COLITA", "PIERNA", "RODILLA", "TOBILLO", "PIE",
    "TALÓN", "PLANTA",

    // Clothing (child terms)
    "REMERA", "CAMISETA", "CAMPERA", "BUZO", "SWEATER", "PULÓVER",
    "PANTALON", "JEAN", "JOGGING", "CALZA", "SHORT", "BERMUDA",
    "POLLERA", "FALDA", "VESTIDO", "ENTERITO", "MAMELUCO", "PIJAMA",
    "CAMISON", "BATA", "BOMBACHA", "CALZON", "CALZONCILLO", "BOXER",
    "MEDIA", "ZAPATILLA", "ZAPATO", "SANDALIA", "OJOTA", "BOTA",
    "PANTUFLA", "GORRO", "GORRA", "SOMBRERO", "BUFANDA", "GUANTE",

    // Nature (simple)
    "SOL", "SOLCITO", "LUNA", "LUNITA", "ESTRELLA", "ESTRELLITA",
    "NUBE", "NUBECITA", "LLUVIA", "GOTITA", "GOTA", "CHARCO",
    "ARCOIRIS", "CIELO", "VIENTO", "BRISA", "TRUENO", "RELAMPAGO",
    "NIEVE", "GRANIZO", "NEVADA", "TORMENTA",
    "ARBOL", "ARBOLITO", "PLANTA", "PLANTITA", "FLOR", "FLORECITA",
    "HOJA", "HOJITA", "RAMA", "RAIZ", "TRONCO", "PASTO",
    "CESPED", "TIERRA", "ARENA", "PIEDRA", "PIEDRITA", "ROCA",
    "MONTAÑA", "CERRO", "COLINA", "VALLE", "RIO", "LAGO",
    "MAR", "PLAYA", "OLA", "ARENA", "CONCHITA", "CARACOL",

    // Vehicles (child terms)
    "AUTO", "AUTITO", "CAMION", "CAMIONCITO", "COLECTIVO", "BONDI",
    "TREN", "TRENCITO", "SUBTE", "METRO", "TAXI", "REMIS",
    "AVION", "AVIONCITO", "HELICOPTERO", "BARCO", "BARQUITO", "LANCHA",
    "MOTO", "BICI", "BICICLETA", "TRICICLO", "MONOPATÍN", "PATINES",
    "AMBULANCIA", "BOMBERO", "CAMION", "GRUA", "EXCAVADORA", "TRACTOR",

 
    // Other Cartoon Characters
    "BOB", "ESPONJA", "PATRICIO", "CALAMARDO", "CANGREJO", "ARENITA",
    "PLANKTON", "GARY", "LARRY", "TIMMY", "COSMO", "WANDA",

    // Superheroes
    "SUPERMAN", "BATMAN", "ROBIN",
    // Nintendo Characters
    "MARIO", "LUIGI",

    // Anime Characters
    "GOKU", "VEGETA", "GOHAN", "GOTEN",

    // ============ 3-DIGIT CODE COVERAGE ============
    // Filling gaps to cover all 000-999 codes

    // 0XX codes (R-X-X)
    "ARROBA", "ROEDOR", "HORROR",
    "RULERO", "RELATOR", "ORÁCULO", "RORCUAL",
    "REFRESCO", "RESORTE", "ARRUGA", "ERUCTO",
    "ORCA", "ARRECIFE", "REGAR", "REGATA", "RUGIDO",
    "ARRITMIA", "ERÓTICO", "REMATE", "ROMBO",

    // ============ CLASH ROYALE ============
    // Troops
    "CABALLERO", "ARQUERAS", "ARQUERA", "GIGANTE", "DUENDE", "DUENDES",
    "GOBLIN", "GOBLINS", "MINERO", "VALQUIRIA", "MUSKETEER", "MOSQUETERA",
    "MAGO", "BRUJA", "ESQUELETOS", "ESQUELETO", "BOMBARDERO", "GIGANTE",
    "GOLEM", "PEKKA", "DRAGON", "DRAGÓN", "BEBE", "BEBÉ", "INFERNAL",
    "GLOBO", "BOMBARDERO", "SABUESO", "LAVAHOUND", "LAVA", "MEGACABALLERO",
    "PRINCIPE", "PRÍNCIPE", "OSCURO", "BANDIDA", "FANTASMA", "REAL",
    "VERDUGO", "EJECUTOR", "LEÑADOR", "CAZADOR", "ELECTROMAGO",
    "ARQUERO", "MÁGICO", "BARBAROS", "BÁRBARO", "BÁRBAROS", "ELITE",
    "MONTAPUERCOS", "CERDO", "JINETE", "CARNERO", "ARIETE", "BATALLA",
    "CHISPITAS", "ELECTRO", "ESPÍRITU", "ESPIRITU", "FUEGO", "HIELO",
    "SANADOR", "CURACIÓN", "TORNADO", "DESCARGA", "RAYO", "COHETE",
    "TERREMOTO", "VENENO", "FURIA", "RABIA", "CLON", "ESPEJO",
    "CONGELACIÓN", "BOLA", "NIEVE", "ZAPPIES", "ZAPADOR", "VOLADOR",
    "MURCIÉLAGO", "MURCIÉLAGOS", "MURCIELAGO", "NOCTURNA", "BRUJA",
    "MADRE", "CLAN", "HORDA", "ESBIRROS", "ESBIRRO", "MEGAESBIRRO",
    "TORRE", "INFIERNO", "TESLA", "MORTERO", "CAÑÓN", "CANON",
    "DISPENSADOR", "CHOZA", "BÁRBARA", "CABAÑA", "DUENDES", "GOBLIN",
    "PRINCESA", "HIELO", "MAGO", "ARQUERAS", "REINA", "REY",
    "CAMPEÓN", "CAMPEONA", "MONJE", "GOLDEN", "DORADO", "CABALLERO",
    "ESQUELÉTICO", "MIGHTY", "PODEROSO", "ARCHER", "QUEEN",

    // Champions & Heroes
    "GOLDEN", "KNIGHT", "SKELETON", "KING", "MIGHTY", "MINER",
    "ARCHER", "QUEEN", "MONK", "LITTLE", "PRINCE",

    // Buildings
    "TORRE", "INFIERNO", "TESLA", "MORTERO", "CAÑÓN", "XARCO",
    "HORNO", "RECOLECTOR", "ELIXIR", "BOMBA", "TUMBA", "LÁPIDA",
    "CHOZA", "BÁRBARA", "CABAÑA", "DUENDE", "FÁBRICA", "ESBIRROS",

    // Spells
    "BOLA", "FUEGO", "FLECHAS", "FLECHA", "DESCARGA", "ZAPS",
    "RAYO", "COHETE", "VENENO", "TERREMOTO", "TORNADO", "CONGELACIÓN",
    "CLON", "FURIA", "ESPEJO", "RABIA", "SANACIÓN", "NIEVE",

    // Other Clash Royale terms
    "COFRE", "LEGENDARIO", "ÉPICO", "RARO", "COMÚN", "CAMPEÓN",
    "ARENA", "LIGA", "TROFEO", "TROFEOS", "CORONAS", "CORONA",
    "ELIXIR", "MANÁ", "CARTA", "CARTAS", "BARAJA", "MAZO",
    "EMOTE", "EMOTICONO", "CLAN", "GUERRA", "BATALLA", "DESAFÍO",
    "TORNEO", "TEMPORADA", "PASE", "ROYALE", "SUPERCELL"
];

// Build the word dictionary
const WORD_DICT = {};

function buildDictionary() {
    const allWords = [...BASE_WORDS, ...EXTENDED_WORDS];
    const seen = new Set();

    for (const word of allWords) {
        const normalized = word.trim().toUpperCase();
        if (seen.has(normalized)) continue;
        seen.add(normalized);

        const code = wordToCode(normalized);
        if (code === "") continue;

        if (!WORD_DICT[code]) {
            WORD_DICT[code] = [];
        }
        WORD_DICT[code].push(normalized);
    }
}

buildDictionary();

// Export for use in app.js
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { WORD_DICT, wordToCode, CODE_MAP };
}
