// Mnemonic System (Spanish Major System)
// R = 0; S, Z = 5;
// L = 1; G = 6;
// D = 2; T = 7;
// M = 3; B, V = 8;
// C, Q, K = 4; N, Ñ = 9;
// COMODINES (wildcards): A, E, I, O, U, X, Y, H, F, J, P, W

const CODE_MAP = {
    'r': '0',
    'l': '1',
    'd': '2',
    'm': '3',
    'c': '4', 'q': '4', 'k': '4',
    's': '5', 'z': '5',
    'g': '6',
    't': '7',
    'b': '8', 'v': '8',
    'n': '9', 'ñ': '9'
};

// Convert word to number code
function wordToCode(word) {
    let code = "";
    const normalized = word.toLowerCase().normalize("NFD").replace(/[\u0301]/g, "");
    for (const char of normalized) {
        if (CODE_MAP[char] !== undefined) {
            code += CODE_MAP[char];
        }
    }
    return code;
}

// All words
const ALL_WORDS = [
    "ORO", "HIELO", "JUDIO", "MAIA", "COPA", "OSO", "FUEGO", "PATO",
    "ABEJA", "PAN", "PILAR",
    "POLLO", "HELADO", "FALDA", "PLUMA",
    "LECHE",
    "LAPIZ",
    "LEGO", "PELOTA", "LOBO", "ALAN", "LEON", "FLAN",
    "XILOFONO", "LUNA", "LANA", "PIEDRA", "HIDRA", "PODER", "DORY", "DOLO",
    "DALI", "DELPO", "DADO", "DEDO", "DUDA", "DAMA", "DUKI", "EDIFICIO",
    "DIOS", "FIDEOS", "DESAFÍO", "DIEGO", "DT", "DIBUJO", "DANI", "DUNA",
    "FODEN", "FUMAR", "MAR", "AMOR", "HOMER", "MARIO", "MILI", "MIEL",
    "POMELO", "MOJADO", "MIEDO", "MEDIA", "MAMA", "MOMIA", "MOCO", "HAMACA",
    "MESA", "MUSEO", "MOUSE", "POMPAS", "MAZO", "MAGO", "MAGIA", "MATE",
    "MOTO", "EMOTE", "PUMBA", "MONO", "JAMON", "MANO", "MONJA", "MONJE",
    "MINA", "MOANA", "MANE", "MUFFIN", "MANÁ", "JOKER", "CULO", "KOALA",
    "CLIP", "CIELO", "COLA", "PICADA", "CODO", "CAIDA", "CAMA", "COMPU",
    "COCA", "CASA", "CAGA", "PACTO", "ACEITE", "COHETE", "CHUPETE", "CUBA",
    "CUEVA", "KOBE", "COBAYO", "CHINO", "CONEJO", "CAJON", "CINE", "OCEANO",
    "OFICINA", "CANOA", "CUNA", "QUEEN", "SURF", "SHERIFF", "ZAFIRO", "SOL",
    "SAL", "ISLA", "SALAH", "ASADO", "ESPADA", "SEDA", "SODA", "ESPUMA",
    "SACO", "WHISKY", "ESQUI", "SHAQ", "OSAKA", "OSOS", "PIZZA", "SUSHI",
    "OASIS", "ZAPPIES", "ZAPS", "SOGA", "ZAPATO", "ESTUFA", "OSITO", "PASTO", "PASTAS",
    "SUBE", "USB", "SONIA", "ESPONJA", "SAXOFON", "PASION", "SUEÑO", "JUGAR",
    "JAGUAR", "YOGUR", "GRIFO", "GRUA", "OGRO", "GARY", "GOL", "AGUILA",
    "GOLF", "GALAXIA", "GUIDO", "HIGADO", "GAUDIO", "GOMA", "AGACHA", "GOKU",
    "GUISO", "GPS", "PEGASO", "GAFAS", "GAGO", "GATO", "FOGATA", "JUGUITO",
    "GOTA", "GUIABA", "POGBA", "GENIO", "IGUANA", "GOHAN", "TORO", "TRAJE",
    "THOR", "TIJERA", "TRAPO", "TROFEO", "TELA", "HOTEL", "TELE", "ATAUD",
    "PATADA", "TIEMPO", "HIPOPOTAMO", "ATOMO", "THIEM", "TACHO", "TACO", "TECHO",
    "FOTOS", "TAZA", "OJOTAS", "TIZA", "FATIGA", "TUTE", "PATITO", "AUTITO",
    "TUBO", "ATUN", "PATIN", "BRUJA", "BRUJO", "BAR", "FIBRA", "BOXER",
    "BARAJA", "PABLO", "VELA", "VOLEY", "VUELO", "BEAL", "BOLA", "ABADE",
    "VIDA", "BOHEMIO", "VACA", "BOCA", "BICI", "HUEVOS", "VASO", "BESO",
    "BOSH", "AVISPA", "BUZO", "VAGA", "BATA", "BOTE", "OVEJITA", "BOTA",
    "BOBE", "BOB", "BEBE", "BEBÉ", "JABON", "AVENA", "VINO", "AVION",
    "OVNI", "BANJO", "BUFFON", "BAÑO", "HENRY", "NEUER", "NORIA", "PAÑUELO",
    "PAÑAL", "PANDA", "WANDA", "NEMO", "ANCHOA", "PANCHO", "ENCHUFE", "NUCA",
    "PINOCHO", "NUEZ", "PINZA", "ENZO", "PANZA", "PING", "PONG", "NATA",
    "FUENTE", "JINETE", "PUENTE", "NAVAJA", "NAVE", "NIEVE", "NUBE", "NINJA",
    "PONNY", "FLORERO", "LARRY", "LEOPARDO", "PALERMO", "LORITO", "POLLERA", "FILLOL",
    "LLAMA", "POLLITO", "LLAVE", "LLUVIA", "HELADERA", "LAMPARA", "PLOMERO", "PALMER",
    "ALMOHADA", "OLIMPIADA", "LIMON", "PULMON", "ALUMINIO", "PELUQUERIA", "PULCERA", "LOCURA",
    "PLACER", "LAPICERA", "LUKAKU", "LECHUZA", "FLECHAS", "LECHUGA", "HALCON", "PELICANO",
    "LASER", "PLASMA", "LISTA", "LASAÑA", "EXPLOSION", "PULGAR", "ALEGRIA", "LAGUNA",
    "ALTAR", "LAUTARO", "POLITICO", "LATIGO", "PELOTITA", "PLATANO", "LIEBRE", "LIBRO",
    "PULÓVER", "ALBUM", "ELVIS", "HAALAND", "PALANCA", "PLANCHA", "LANCHA", "LENGUA",
    "ELEFANTE", "LENTEJA", "PLANTA", "LENTE", "PLANETA", "LUNITA", "FEDERER", "DARDO",
    "DORADO", "DRAKE", "PODEROSO", "PIEDRITA", "DRON", "DARWIN", "DOLOR", "DULCE",
    "DELFIN", "DELFINO", "PADDLE", "DIADEMA", "DEDITO", "DIMARIA", "DOMINO", "DEMONIO",
    "DECK", "DISPARO", "DISCO", "DEPOSITO", "DISNEY", "DYBALA", "DUENDE", "DANZA",
    "DIENTE", "DONUT", "MURRAY", "AMERICA", "MARIPOSA", "MORSA", "MORGUE", "MARGE",
    "MUERTE", "MEJILLA", "MUELLE", "MELODIA", "MELON", "MOLINO", "MADERA", "MADRE",
    "MODELO", "MEDICO", "MEDIAS", "MEDUSA", "MEMORIA", "MECHERO", "MOCHILA", "MICKEY",
    "MESERO", "MISIL", "MUSLO", "MAUSOLEO", "MOSCA", "MUSICO", "MESSI", "MÁGICO",
    "MIGHTY", "MOTOR", "METRO", "METAL", "HOMBRO", "FIAMBRE", "EMBAJADA", "EMBIID",
    "MINERO", "MINER", "EMPANADA", "MONEDA", "EMINEM", "MANCHA", "MUÑECA", "MUNICIPIO",
    "MONK", "MAYONESA", "IMANES", "MANGO", "MANGA", "MENTA", "PIMIENTA", "MANTA",
    "MENTE", "MOUNT", "MONITO", "CARRO", "CHURRO", "CURRY", "CERRO", "CIRUELA",
    "CORAL", "CHARLY", "CRAYOLA", "ACUARELA", "CERDO", "CREMA", "KARMA", "CIRCO",
    "CARICIA", "CHARCO", "CRUZ", "CEREZA", "CHORIZO", "KROOS", "CRESPO", "CARTA",
    "PICAPORTE", "KARATE", "CERATI", "CARPETA", "CUARTO", "CUERVO", "CUERNO", "CARNE",
    "CRANEO", "CIRUJANO", "CORONA", "CARIÑO", "CRAYÓN", "CUELLO", "CEPILLO", "CAPILLA",
    "CELLO", "CALDO", "COLUMPIO", "CHALECO", "COLCHA", "COLISEO", "ECLIPSE", "CALZA",
    "COLITA", "CLAVIJA", "CLUB", "COLINA", "CLON", "CLAN", "CUADRO", "CADERA",
    "CODIGO", "CADENA", "CAMARA", "CAMPERA", "CAMISA", "KEMPES", "COMPAS", "CIEMPIÉS",
    "COMETA", "CAMBIO", "CAMPANA", "CHAMPAN", "CHIMENEA", "CAMION", "CAIMÁN", "CAMPEÓN",
    "CAMPEONA", "COMÚN", "CUCHARA", "CHICLE", "CICLOPE", "CUPCAKE", "CHAQUETA", "PECECITO",
    "CACHETE", "COCINA", "CESPED", "COSMO", "CASCO", "KIOSCO", "PICASSO", "CASITA",
    "CASINO", "CISNE", "CIGUEÑA", "CAFETERA", "ACTOR", "EJECUTOR", "KETCHUP", "CAPITAN",
    "ACEITUNA", "CHUPETÍN", "CABRA", "CEBRA", "COBRE", "CABLE", "CABEZA", "CUBOS",
    "CABINA", "CAVANI", "CABAÑA", "CANARIO", "CANELA", "CANCHA", "KING", "CINTA",
    "QUINTA", "KANTE", "CONEJITO", "CAÑON", "CAÑÓN", "CANON", "ZORRO", "PIZARRA",
    "SIERRA", "SORDA", "HAZARD", "SHREK", "SUAREZ", "SUERTE", "SHORT", "ESPÍRITU",
    "ESPIRITU", "SHARAPOVA", "SIRENA", "SERENA", "SILLA", "PASILLO", "ESPALDA", "SALTO",
    "SELVA", "SALON", "ZEPPELIN", "ZAPADOR", "ZIDANE", "SEMAFORO", "SAMURAI", "SAMUEL",
    "ZOMBI", "ZOMBIE", "SIMEONE", "AZUCAR", "SHAKIRA", "OSCURO", "FISCAL", "ESCUELA",
    "SCOLA", "ESCUDO", "PESCADO", "ESCOBA", "PISCINA", "PUZZLE",
    "ZAPATERO", "SUETER", "STEREO", "PASTEL", "PISTOLA", "HOSPITAL", "HOSTAL",
    "ESTADIO", "AZTECA", "OSITOS", "PESTAÑA", "SOTANO", "ZEBRA", "SAVIOLA",
    "SABUESO", "SUBTE", "SABANA", "ZANAHORIA", "SONAJERO", "SANDIA", "ESPINACA", "GORRA",
    "GORRO", "GUERRA", "GORILA", "GUARDIA", "GUARIDA", "HAGRID", "GARCIA", "GRIEGO",
    "GEORGE", "GRITO", "GRANO", "GRANJA", "GREEN", "GLORIA", "GALLO", "GOLEM",
    "IGLESIA", "GLOBO", "JUGADOR", "GOMITA", "AGUACATE", "GUSANO", "GATITO", "GOTITA",
    "GOTEN", "GNOMO", "GANCHO", "GANSO", "GUANTE", "TORERO", "TORRE", "TIERRA",
    "TERRY", "TERMO", "TROMPO", "TRUCO", "TRUCHA", "TUERCA", "PATRICIO", "TIJERAS",
    "TORSO", "TROFEOS", "TARJETA", "TORTA", "TARTA", "TREN", "TRINEO", "TORNEO",
    "TRUENO", "TOALLA", "ATLETA", "TELEFONO", "TALON", "TALÓN", "TEMOR", "TEMPERA",
    "TEMPLO", "TIMMY", "TOMATE", "TUMBA", "TIMON", "ETIQUETA", "TOCINO", "TESLA",
    "TAXISTA", "AUTOPISTA", "TYSON", "TIGRE", "FOTOGRAFO", "TEATRO", "TATUM", "PATITAS",
    "TOTTI", "TITANIO", "TABLA", "FUTBOL", "PATOVICA", "AUTOBUS", "TEVEZ", "TUNEL",
    "TIENDA", "TANQUE", "TENIS", "PATINES", "TANGA", "PATINETA", "BURRO", "BERRO",
    "BRUJULA", "VERDE", "BIROME", "BARCO", "FABRICA", "FÁBRICA", "BRAZO", "BRISA",
    "VIRUS", "ABRAZO", "BART", "BARBIE", "BARBA", "VERON", "BROWN", "FIBRÓN",
    "VELERO", "VALLE", "BALDE", "BOLICHE", "OBLAK", "BOLSA", "BLUSA", "BOLSO",
    "VILAS", "VIOLETA", "BALON", "VIOLIN", "BOXEADOR", "VIDRIO", "VADER", "VODKA",
    "BODEGA", "VAMPIRO", "BOMBA", "BOOKER", "VAQUITA", "BACON", "VACUNA", "BASURA",
    "BOSQUE", "BUZZ", "ABOGADO", "BIGOTE", "VEGETA", "BATERIA", "BATIDO", "BOTAS",
    "BOTON", "BABERO", "BABOSA", "BAÑERA", "BANDA", "BUFANDA", "BONDI", "BANCO",
    "BEYONCE", "VENUS", "VIENTO", "BANANA", "VENENO", "NORRIE", "NARIZ", "ENERGIA",
    "NARUTO", "NARANJA", "NEURONA", "INFIERNO", "ANILLO", "PANDERO", "NADAL", "NEYMAR",
    "ANCLA", "PINCEL", "PANQUEQUE", "PANCHOS", "NOCIONI", "INIESTA", "NEGRO", "HANGAR",
    "ANGEL", "JUNGLA", "PINGUINO", "NUTRIA", "PANTERA", "PINTURA", "PINTOR", "PANTUFLA",
    "ANTEOJOS", "PUÑETAZO", "ANTENA", "PANTANO", "NEWTON", "NEVERA", "NIEBLA", "NEVADA",
    "ANUNCIO", "FLORECITA", "LADRON", "LAMPARD", "ALMACEN", "LIMUSINA", "ALFOMBRA", "FLAMINGO",
    "ALCARAZ", "ALACRAN", "ALCALDE", "LICUADORA", "FELICIDAD", "HELICOPTERO", "ELECTRO", "ALISSON",
    "PLASTICO", "ELASTICA", "LAGARTO", "LAGARTIJA", "PLATAFORMA", "LITTLE", "LIBRERIA", "ALVAREZ",
    "LIBRETA", "LEBRON", "LIBÉLULA", "LAVADORA", "LAVADERO", "ALBAÑIL", "LAVAHOUND", "LIVING",
    "LEONARD", "LEÑADOR", "LONCHERA", "LEONCITO", "LENTES", "ELEFANTITO", "PLANTITA", "EDWARDS",
    "DURAZNO", "DRAGON", "DRAGÓN", "DURANT", "DIAMANTE", "DOCTOR", "DJOKOVIC", "DESIERTO",
    "DESTINO", "DONALD", "DUENDES", "DONCIC", "DUNCAN", "DINOSAURIO", "DIENTES", "DIENTITO",
    "MORRON", "AMARILLO", "MERLUZA", "MARILYN", "EMPERADOR", "MIRADOR", "MORDIDA", "MARADONA",
    "MARMOL", "MAREMOTO", "MERCADO", "MARACAS", "MARIQUITA", "IMPRESORA", "MORTERO", "MARATON",
    "MARINERO", "MORANT", "MULLER", "MILITAR", "MALETIN", "MILANESA", "MODRIC", "MADONNA",
    "MAMELUCO", "MAMADERA", "MICROFONO", "MECEDORA", "MECANICO", "MOZART", "MASCARA", "MUSCULO",
    "MOSQUITO", "MEZQUITA", "MAESTRO", "HAMSTER", "MOSTAZA", "EMOTICONO", "OMBLIGO", "WEMBANYAMA",
    "MANZANA", "MANSION", "MANGUERA", "MONITOR", "MINOTAURO", "MANTEL", "MANTECA", "MENTON",
    "MONTAÑA", "MONOPATÍN", "OMNIBUS", "CARRERA", "CARRETA", "CARRITO", "CERDITO", "ACORDEON",
    "CARAMELO", "CERAMICA", "CIRCULO", "CARCEL", "CARACOL", "CIRCUITO", "KRAKEN", "CURACIÓN",
    "CRESTA", "CORAZON", "CARTERA", "CARTERO", "CARTEL", "CUARTEL", "KARATECA", "CERTEZA",
    "COURTOIS", "CARTAS", "CORTINA", "CARTÓN", "CEREBRO", "CERVEZA", "CORBATA", "CARBON",
    "CARNERO", "CORONAS", "CLERC", "COLIFLOR", "COLLAR", "CELULAR", "CALLEJON", "CALAMARO",
    "COLUMNA", "ACOLCHADO", "COLCHON", "CALESITA", "CALZON", "COLIBRI", "CALABAZA", "CALABOZO",
    "CUADERNO", "CAMELLO", "CAMALEON", "COMEDOR", "COMISARIA", "CAMPAZZO", "CAMISETA", "CAMISON",
    "CUMBRE", "CEMENTO", "CACEROLA", "CUCARACHA", "CUCHILLO", "CHOCOLATE", "COCHECITO", "CACTUS",
    "COCINERO", "CAZADOR", "CASCADA", "CHISPITAS", "ACTRIZ", "ICEBERG", "CABALLO", "CEBOLLA",
    "CABELLO", "EXCAVADORA", "CHEWBACCA", "CANILLA", "CANDADO", "CANICAS", "CONCHITA", "CANCION",
    "CONSOLA", "CANGURO", "CANGREJO", "CANIGGIA", "KNIGHT", "CENTAURO", "CINTURA", "CENTRO",
    "CIENTIFICO", "PIZARRÓN", "ASPIRADORA", "SARDINA", "SUPERMAN", "SURFISTA", "SARTEN", "ESPERANZA",
    "SERPIENTE", "SILLON", "SOLDADO", "SALMON", "SALCHICHA", "SOLCITO", "ZOOLOGICO", "SILBATO",
    "SILENCIO", "SMART", "SOMBRA", "ESCARABAJO", "ESCORPION", "ESCALERA", "ESCALADA", "PSICOLOGO",
    "ESQUELETO", "SECADOR", "ESCUADRA", "SCOOTER", "SCOTCH", "ESCENARIO", "SASTRE", "SISTEMA",
    "ESGRIMA", "ZAPATILLA", "SATELITE", "ESTOMAGO", "JOYSTICK", "ESTACION", "ESTABLO", "ESTANTE",
    "ESBIRRO", "ZVEREV", "SABIDURIA", "SABATINI", "SENADOR", "SANDALIA", "SANACIÓN", "SENSOR",
    "SANGRE", "SINAGOGA", "SANTUARIO", "ZANETTI", "SINNER", "GRILLO", "GARDEL", "GRANADA",
    "GARNACHO", "GRANIZO", "GERENTE", "GOLLUM", "GALLETA", "GALLINA", "GOLDEN", "GLACIAR",
    "GLOBITO", "GIMNASIO", "PEGAMENTO", "GUISANTE", "JOGGING", "GIGANTE", "GUITARRA", "GOBLIN",
    "GANDALF", "GUANTES", "GINEBRA", "GINOBILI", "GIANNIS", "TERRAZA", "TROLL", "TRAPEADOR",
    "TROMPETA", "TERCIOPELO", "TARZAN", "TIJERITAS", "TORTUGA", "TERNERA", "TORNADO", "TRONCO",
    "TRANVIA", "TELEFÉRICO", "TALLER", "TALADRO", "TELESCOPIO", "ATLANTA", "TEMPORADA", "THOMPSON",
    "TAMBOR", "TECLADO", "TOSTADA", "TSUNAMI", "TABURETE", "TIBURON", "TOBILLO", "TABLET",
    "TOBOGAN", "TENEDOR", "TENISTA", "EXTINTOR", "BURRITO", "VERDAD", "VERDUGO", "BERMUDA",
    "BROCOLI", "BARQUITO", "BRITNEY", "BÁRBARO", "BURBUJAS", "BRONCE", "BILLAR", "BALLENA",
    "VOLADOR", "VALDANO", "VALQUIRIA", "BLOCK", "BLOQUES", "BALCON", "BOLITAS", "BALNEARIO",
    "BLANCO", "VOLANTE", "BOMBERO", "BOMBACHA", "BECKHAM", "VICTORIA", "VIKINGO", "BIZCOCHO",
    "BASQUET", "VESTIDO", "BUTLER", "BOTELLA", "BEATLES", "BATIDORA", "BATMAN", "HABITACION",
    "BEETHOVEN", "BIBERON", "VAINILLA", "BANDERA", "BANDIDA", "BUNKER", "VINICIUS", "AVIONCITO",
    "BENZEMA", "VINAGRE", "VENTANA", "ENFERMERA", "NARICITA", "INFERNAL", "NADADOR", "UNICORNIO",
    "ENSALADA", "ANSIEDAD", "EINSTEIN", "ANGUSTIA", "INGENIERO", "ANTORCHA", "ENTERITO", "NUTELLA",
    "PANTUFLAS", "PANTALON", "NATACION", "FANTASMA", "NUBECITA", "LILLARD", "LADRILLO", "LOMBRIZ",
    "ALMENDRA", "LUCIÉRNAGA", "LOCOMOTORA", "ELECTRODO", "PLASTICOLA", "LEGENDARIO", "LABORATORIO", "LABERINTO",
    "LAVAPLATOS", "ALBONDIGA", "LONDRES", "LEWANDOWSKI", "PLANKTON", "LANGOSTA", "LONGANIZA", "LINTERNA",
    "DORMITORIO", "DIRECTOR", "DELANTAL", "DICTADOR", "DESCARGA", "DISCOTECA", "DETECTIVE", "DENTISTA",
    "MERMELADA", "MURCIELAGO", "MURCIÉLAGO", "MARCADOR", "MERCEDES", "MARTILLO", "MILLONARIO", "MEDVEDEV",
    "MICROSCOPIO", "MUSKETEER", "MOSQUETERA", "MAGDALENA", "FIAMBRERAS", "HAMBURGUESA", "AMBULANCIA", "MANDARINA",
    "MONUMENTO", "MONASTERIO", "MONSTRUO", "CORREDOR", "CERRADURA", "CARRUSEL", "CRISTAL", "CARTULINA",
    "CARTUCHERA", "CARNICERO", "CARNICERIA", "CARPINTERO", "CLARINETE", "CALAMARDO", "CALAMARES", "CALEFACTOR",
    "COLECTIVO", "CALCETIN", "COLGADOR", "CALENDARIO", "COMEDIANTE", "COMPUTADORA", "CAMBIASSO", "CAMIONCITO",
    "CEMENTERIO", "CHOCOLATADA", "CHOCOLATÍN", "COCODRILO", "CASILLAS", "COSTILLA", "CASTILLO", "CATEDRAL",
    "CABALLERO", "CABALLITO", "CANILLERA", "CHANDLER", "CONCIERTO", "CENICIENTA", "CONTROL", "CONTRABAJO",
    "CINTURON", "CANTANTE", "CONVENTO", "SUPERCELL", "SERVIDOR", "SALTARIN", "SPIDERMAN", "ESMERALDA",
    "SIMPSONS", "SOMBRERO", "SACERDOTE", "ESCRITORIO", "ESCRITOR", "ESQUELÉTICO", "ESQUELETOS", "SKELETON",
    "ASCENSOR", "SACAPUNTAS", "PASSARELLA", "ESTRELLA", "HISTORIADOR", "ASTRONAUTA", "ZAPATILLAS", "ESTUDIANTE",
    "WESTBROOK", "ESBIRROS", "SABALENKA", "SUBMARINO", "SANDALIAS", "GERRARD", "GARGANTA", "GRAVEDAD",
    "GARBANZO", "GALLARDO", "GALLETITA", "GLADIADOR", "GASOLINERA", "GOBLINS", "TERREMOTO", "TRAMPOLIN",
    "TORMENTA", "TRICICLO", "TRACTOR", "TRABAJADOR", "TORNILLO", "TRENECITO", "TRENCITO", "TRIANGULO",
    "TELEVISOR", "TELEVISION", "ATLANTIDA", "TOSTADORA", "TSITSIPAS", "TIGRECITO", "FUTBOLISTA", "BORRADOR",
    "BERMUDAS", "BERGKAMP", "BARBAROS", "BÁRBAROS", "BARBILLA", "BILLETERA", "VOCALISTA", "BICICLETA",
    "VECINDARIO", "BUSQUETS", "VETERINARIO", "BATISTUTA", "BIBLIOTECA", "VENDEDOR", "NOCTURNA", "NOSTALGIA",
    "NUGGETS", "ANTARTIDA", "INTERNET", "INTESTINO", "PENITENCIARIA", "LAPROVITTOLA", "ELECTROMAGO", "DUMBLEDORE",
    "DISPENSADOR", "MURCIÉLAGOS", "MACARRONES", "MICROONDAS", "MEGAESBIRRO", "MONTAPUERCOS", "CROISSANT", "CALCULADORA",
    "CUATRICICLO", "CONDUCTOR", "CONGELACIÓN", "SUPERMERCADO", "SERVILLETA", "ESTRELLITA", "GRIEZMANN", "GOLONDRINA",
    "GUITARRISTA", "GOBERNADOR", "TERRORISTA", "TERMOMETRO", "VOLDEMORT", "BOMBARDERO", "OBSERVATORIO", "BINOCULARES",
    "VENTILADOR", "NALBANDIAN", "INGLATERRA", "PANTORRILLA", "INTERRUPTOR", "UNIVERSIDAD", "INVERNADERO", "ELECTRICISTA",
    "MEGACABALLERO", "CALZONCILLO", "SALTAMONTES", "BLANCANIEVES", "INSTRUCTOR", "EXTRATERRESTRE", "DESTORNILLADOR", "PERRO",
    "RELOJ", "RUEDA", "ARMA", "ARCO", "ROSA", "ORUGA", "RATA", "RUBIA",
    "ARAÑA", "PARLANTE", "ROLLO", "REPOLLO", "PARAGUAS", "RIVER", "RACING", "ARGENTINA",
    "ARTICULO", "FRENTE", "ARENITA", "PARACAIDAS", "FRUTILLA", "REMERA", "ARMARIO", "ORNITORRINCO",
    "PRINCESA", "RACHEL", "ORÁCULO", "ROSS", "JERSEYS", "ARDILLA", "RODILLA", "ARMADILLO",
    "HORMIGA", "RATON", "RINOCERONTE", "ARROZ", "FRAMBUESA", "PRETZEL", "RABANO", "ROBIN",
    "RAVIOLI", "ARBOL", "RISOTTO", "JARRON", "ORDENADOR", "REGADERA", "REGLA", "REVISTA",
    "ARBUSTO", "RINON", "ARBITRO", "ARQUITECTO", "ARTISTA", "FARMACEUTICO", "JARDINERO", "PERIODISTA",
    "PRESIDENTE", "PRINCIPE", "RANCHO", "WAWRINKA", "RENACUAJO", "PRÍNCIPE", "PRINCE", "PROFESOR",
    "FREEZER", "PROGRAMADOR", "REPORTERO", "ROBOT", "ORBITA", "AEROPUERTO", "PERRITO", "APARTAMENTO",
    "FARMACIA", "FORTALEZA", "FRONTERA", "HIPERMERCADO", "JARDIN", "JORDAN", "HARDEN", "PIRAMIDE",
    "PORTAL", "PRISION", "PROSTIBULO", "RESTAURANTE", "RINCON", "FURGONETA", "ARQUERO", "ARQUERA",
    "ARCHER", "PORTERO", "RAQUETA", "ERUCTO", "RUGBY", "ORQUESTA", "HURACAN", "PRADERA",
    "RADAR", "ROEDOR", "PROCESADOR", "REACTOR", "ORGULLO", "RECUERDO", "ARCILLA", "PORCELANA",
    "IRONMAN", "RONALDO", "HERMIONE", "FIRMINO", "RAPUNZEL", "RONALDINHO", "RAMOS", "REMIS",
    "RODRIGO", "RIQUELME", "REDONDO", "ORTEGA", "IRVING", "PRIGIONI", "RUBLEV", "FRITZ",
    "FRITAS", "ROMPECABEZAS", "RESBALIN", "RATONCITO", "PIRULETA", "FRAZADA", "RADIADOR", "REMOTO",
    "REMATE", "AURICULAR", "REPASADOR", "ARCOIRIS", "ARQUERAS", "RELAMPAGO", "ARBOLITO", "ARROBA",
    "HORROR", "RULERO", "RELATOR", "RORCUAL", "REFRESCO", "RESORTE", "ARRUGA", "ARRECIFE",
    "REGAR", "REGATA", "RUGIDO", "ARRITMIA", "ERÓTICO", "ROMBO", "RECOLECTOR",
];

// Build the word dictionary
const WORD_DICT = {};

function buildDictionary() {
    const seen = new Set();

    for (const word of ALL_WORDS) {
        const normalized = word.trim().toUpperCase();
        if (seen.has(normalized)) continue;
        seen.add(normalized);

        const code = wordToCode(normalized);
        if (code === "") continue;

        if (!WORD_DICT[code]) {
            WORD_DICT[code] = [];
        }
        WORD_DICT[code].push(normalized);
    }
}

buildDictionary();

// Export for use in app.js
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { WORD_DICT, wordToCode, CODE_MAP };
}

