// R = 0; S, Z = 5;
// L = 1; G = 6;
// D = 2; T = 7;
// M = 3; B, V = 8;
// C, Q, K = 4; N, Ñ = 9;
// COMODINES: A, E, I, O, U, X, Y, 
// AAAAOOOEEEIIIUUUFFJJPPYXH

const diccBase = ["ORO", "HIELO", "JUDIO", "MAIA", "COPA", "SEXO", "AGUA", "TIO", "UBA", "PEON", "PERRO", "RELOJ", "RUEDA", "ARMA", "ROCO", "ROSA", "ORGIA", "RATA", "RUBIA", "RANA", "PILAR", "LILA", "HELADO", "PLUMA", "POLICÍA", "ALAS", "LAGO", "LATA", "LOBO", "ALAN", "PIEDRA", "DOLO", "DADO", "DAMA", "DUKI", "DIOS", "DIEGO", "DT", "DIBUJO", "DANI", "FUMAR", "MILI", "MOJADO", "MAMA", "MOCO", "MESA", "MAGO", "MATE", "PUMBA", "MONO", "CARO", "CULO", "PICADA", "CAMA", "COCA", "CASA", "CAGA", "PACTO", "CUBA", "CHINO", "SURF", "SOL", "ASADO", "ESPUMA", "SACO", "OSOS", "SOGA", "ZAPATO", "SUBE", "SONIA", "JUGAR", "GOL", "GUIDO", "GOMA", "AGACHA", "GUISO", "GAGO", "GATO", "GUIABA", "GENIO", "TORO", "TELA", "ATAUD", "TIEMPO", "TACHO", "FOTOS", "FATIGA", "TUTE", "TUBO", "ATUN", "BRUJA", "PABLO", "ABADE", "BOHEMIO", "VACA", "HUEVOS", "VAGA", "BATA", "BOBE", "JABON", "PEINAR", "ANAL", "PANDA", "NEMO", "NACHO", "NASA", "HONGO", "PIÑATA", "NUBE", "ENANO"]

const agregados = ["MARADONA","PARLANTE","TENEDOR","TOALLA","CUADRO","BOLSA","BARBIE","TRUCO", "ROLLO","CABLE","COMPUTADORA ","PATOVICA","PARAGUAS","BALDE","CANILLA","ESCUDO", "DIENTES","CANILLERA","ABOGADO","SORDA","TABLA","RIVER","ATLANTA","RACING", "AMBULANCIA", "ÁNGEL", "ANILLO", "ANTÁRTIDA", "ANTORCHA", "ARGENTINA", "ARTÍCULO", "ATLÁNTIDA", "AZTECA", "BALLENA", "BANCO", "BANDA", "BARCO", "BATERÍA", "BOMBA", "BOSQUE", "BOTELLA", "BOTÓN", "BRAZO", "CABALLERO", "CABEZA", "CACTUS", "CADENA", "CÁMARA", "CAMBIO", "CAMPANA", "CARRERA", "CARRO", "CARTA", "CASCO", "CASINO", "CEMENTERIO", "CENTAURO", "CHOCOLATE", "CIENTÍFICO", "CINTA", "CINTURÓN", "CÍRCULO", "COCINERO", "CÓDIGO", "CANGURO", "CONCIERTO", "CORREDOR", "CRESTA", "CRUZ", "CUCHILLO", "CUELLO", "CUERNO", "DIAMANTE", "DIENTE", "DINOSAURIO", "DISCO", "DRAGÓN", "DUENDE", "EMBAJADA", "EMPERADOR", "ENFERMERA", "ESCORPIÓN", "ESTADIO", "ESTRELLA", "ETIQUETA", "FRENTE", "GANCHO", "GIGANTE", "GRANADA", "GRANO", "GRIEGO", "HELICÓPTERO", "INGLATERRA", "LÁSER", "LÁTIGO", "LENGUA", "LIMUSINA", "LISTA", "LLAVE", "LONDRES", "MANCHA", "MÁSCARA", "SUBTE", "MICROSCOPIO", "COLUMNA", "MISIL", "MORTERO", "MOTOR", "CORAZÓN", "PANTALLA", "PARACAÍDAS", "MODELO", "DOCTOR", "MAESTRO", "MILLONARIO", "SOLDADO", "BANANA", "MANZANA", "FRUTILLA", "MORRON", "ZANAHORIA", "TOMATE", "MANGO", "AMARILLO", "NARANJA", "VERDE", "VIOLETA", "BLANCO", "NEGRO", "VESTIDO", "BERMUDAS", "JOGGING", "ZAPATILLA", "MEDIAS", "CALZON", "TANGA", "PANTUFLAS", "CAMISA", "GORRA", "REMERA", "SWEATER", "GUANTES", "ORNITORRINCO", "CABALLO", "GUSANO", "GOLONDRINA", "PINGÜINO", "LLAMA", "UNICORNIO", "SERPIENTE", "SIRENA", "PRINCESA", "SUPERMAN", "LADRÓN", "VAMPIRO", "BATMAN", "LINTERNA", "SPIDERMAN", "CAPITAN", "AMÉRICA", "EXTRATERRESTRE", "FANTASMA", "BRITNEY", "BEATLES", "MARILYN", "CHANDLER", "RACHEL", "ROSS"]




